In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
print("Imported All")

Imported All


In [2]:
train_df = pd.read_csv('FullDataSet/Train.csv')
print(len(train_df))
train_df.head()

500


Sr                                             Title             Singer  \
0   1                                     All Messed Up             Sum 41   
1   2                                All Nightmare Long          Metallica   
2   3                    American Idiot (Album Version)          Green Day   
3   4                                       Angry Again           Megadeth   
4   5  Annihilation By The Hands Of God (Album Version)  Roadrunner United   

   Length Target                                               Text  
0     164  angry  Another day wasted out of time I can't get out...  
1     477  angry  Crawl from the wreckage one more time Horrific...  
2     176  angry  Don't wanna be an American idiot.  Don't want ...  
3     242  angry  The more of you that I inspect The more of me ...  
4     333  angry  The prophets of God have left you solaced inde...

In [3]:
test_df = pd.read_csv('FullDataSet/Test.csv')
print(len(test_df))
test_df.head()

378


Sr             Title      Singer  Length Target  \
0   1  'Till I Collapse      Eminem     299  angry   
1   2        25 To Life      Eminem     644  angry   
2   3    A Century Ends  David Gray     308  angry   
3   4           A N I C      Sum 41      41  angry   
4   5          Rain Man      Eminem     320  angry   

                                                Text  
0  Sometimes you just feel tired, feel weak When ...  
1  too late for the other side caught in a change...  
2  Cast your eyes into the distance Try to focus ...  
3  Look like ass, smell like shit why are you suc...  
4  You find me offensive I find you offensive for...

In [4]:
# train_df.drop(['Sr','Title','Singer','Length'],axis=1,inplace=True)
# test_df.drop(['Sr','Title','Singer','Length'],axis=1,inplace=True)

In [5]:
#Removing StopWords  
import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
lemmatizer = WordNetLemmatizer()

In [6]:
sentences = []
# count=0
for sent in train_df['Text']:
#     print(count)
    sent = re.sub('[^a-zA-Z]', ' ',sent)
    sent = sent.lower()
    sent = sent.split()
    sent = [ lemmatizer.lemmatize(word) for word in sent if word not in set(stopwords.words('english')) ]
    sent = ' '.join(sent)
    sentences.append(sent)
#     count+=1
train_df['new_text'] = sentences

In [7]:
sentences = []
# count=0
for sent in test_df['Text']:
#     print(count)
    sent = re.sub('[^a-zA-Z]', ' ',sent)
    sent = sent.lower()
    sent = sent.split()
    sent = [ lemmatizer.lemmatize(word) for word in sent if word not in set(stopwords.words('english')) ]
    sent = ' '.join(sent)
    sentences.append(sent)
#     count+=1
test_df['new_text'] = sentences

In [8]:
train_df['Target'].value_counts()

relaxed    125
angry      125
happy      125
sad        125
Name: Target, dtype: int64

In [9]:
test_df['Target'].value_counts()

happy      106
relaxed    101
sad         99
angry       72
Name: Target, dtype: int64

In [10]:
train_df['Target'] 

0        angry
1        angry
2        angry
3        angry
4        angry
        ...   
495    relaxed
496    relaxed
497    relaxed
498    relaxed
499    relaxed
Name: Target, Length: 500, dtype: object

In [11]:
train_df['Target'] = train_df['Target'].map({'angry': 0 ,'sad':1, 'relaxed':2 , 'happy': 3} ) 

In [12]:
test_df['Target'] = test_df['Target'].map({'angry': 0 ,'sad':1, 'relaxed':2 , 'happy': 3} ) 

In [13]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer 

In [18]:
import pickle
tf = TfidfVectorizer(max_features=5000)
df1 = tf.fit_transform(train_df['Text']).toarray()
pickle.dump(tf,open("feature.pkl","wb"))

In [19]:
df2 = tf.transform(test_df['Text']).toarray()

In [20]:
df1 = pd.DataFrame(df1)
df1 = pd.concat([train_df['Target'],df1],axis=1)

In [21]:
df2 = pd.DataFrame(df2)
df2 = pd.concat([test_df['Target'],df2],axis=1)

In [22]:
df1

Target    0    1    2    3    4    5    6    7    8  ...  4990  4991  \
0         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
..      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
495       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
496       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
497       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
498       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
499       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

     4992  4993  4994  4995  4996  4997  4998  4999  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...  
495   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
496   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
497   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
498   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
499   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[500 rows x 5001 columns]

In [23]:
df2

Target    0    1    2    3    4    5    6    7    8  ...  4990  4991  \
0         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4         0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
..      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
373       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
374       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
375       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
376       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
377       2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

     4992  4993  4994  4995  4996  4997  4998  4999  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...  
373   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
374   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
375   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
376   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
377   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[378 rows x 5001 columns]

In [24]:
#MODEL

In [25]:
from sklearn.ensemble import GradientBoostingClassifier

In [26]:
model = GradientBoostingClassifier()

In [27]:
model.fit(df1.drop("Target",axis=1),df1['Target'])

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [28]:
y_predicted = model.predict(df2.drop("Target",axis=1))

In [29]:
confusion_matrix(df2['Target'],y_predicted)

array([[54,  9,  3,  6],
       [12, 50, 19, 18],
       [10, 24, 52, 15],
       [ 8, 19, 26, 53]], dtype=int64)

In [30]:
accuracy_score(df2['Target'],y_predicted)

0.5529100529100529

In [31]:
from sklearn.naive_bayes import MultinomialNB

In [32]:
model = MultinomialNB()

In [33]:
model.fit(df1.drop("Target",axis=1),df1['Target'])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
y_predicted = model.predict(df2.drop("Target",axis=1))

In [35]:
confusion_matrix(df2['Target'],y_predicted)

array([[49, 20,  2,  1],
       [ 5, 72, 17,  5],
       [ 1, 48, 44,  8],
       [ 6, 40, 25, 35]], dtype=int64)

In [36]:
accuracy_score(df2['Target'],y_predicted)

0.5291005291005291

In [37]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [38]:
model.fit(df1.drop("Target",axis=1),df1['Target'])

C:\Users\pramod\.conda\envs\env_pytorch\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\pramod\.conda\envs\env_pytorch\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [39]:
y_predicted = model.predict(df2.drop("Target",axis=1))

In [40]:
confusion_matrix(df2['Target'],y_predicted)

array([[56, 10,  3,  3],
       [12, 49, 22, 16],
       [ 7, 26, 44, 24],
       [16, 14, 23, 53]], dtype=int64)

In [41]:
accuracy_score(df2['Target'],y_predicted)

0.5343915343915344

In [42]:
from sklearn.svm import SVC
model = SVC()

In [43]:
model.fit(df1.drop("Target",axis=1),df1['Target'])

C:\Users\pramod\.conda\envs\env_pytorch\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [44]:
y_predicted = model.predict(df2.drop("Target",axis=1))

In [45]:
confusion_matrix(df2['Target'],y_predicted)

array([[56, 11,  3,  2],
       [ 9, 51, 30,  9],
       [ 8, 31, 46, 16],
       [24, 26, 23, 33]], dtype=int64)

In [46]:
accuracy_score(df2['Target'],y_predicted)

0.49206349206349204

In [47]:
#DumpingOut Trained Models

In [48]:
import pickle

f1 = 'GradientBoostingClassifier.sav'
f2 = 'MultinomialNB.sav'
f3 = 'LogisticRegression.sav'
f4 = 'SVC.sav'

In [49]:
filehandler = open(f4,"wb")
pickle.dump(model,filehandler)
filehandler.close()